import { specialCharacter } from './char'

export const toolbarItems = [
    'undo',
    'redo',
    '|',
    'heading',
    'fontFamily',
    'fontSize',
    '|',
    'formatPainter',
    'removeFormat',
    'bold',
    'italic',
    'underline',
    'strikethrough',
    'superscript',
    'subscript',
    'code',
    '|',
    'fontColor',
    'highlight',
    '|',
    'numberedList',
    'bulletedList',
    'checklist',
    'table',
    '|',
    'alignLeft',
    'alignCenter',
    'alignRight',
    'alignJustify',
    '|',
    'increaseIndent',
    'decreaseIndent',
    '|',
    'link',
    // 'image',
    // emoji,
    specialCharacter,
    'codeBlock',
    'equation',
    // 'video',
    // 'twitter',
    'blockQuote',
    'paragraph',
    'hr',
    '|',
    'selectAll',
    // helloWorld,
];
